hostname: jerkod.is-a.dev

web:
  image:
    repository: ghcr.io/jerkod/portfolio-web
    tag: ""
  replicas: 2
  resources:
    requests: { cpu: 10m, memory: 32Mi }
    limits:   { cpu: 50m, memory: 64Mi }

api:
  image:
    repository: ghcr.io/jerkod/portfolio-api
    tag: ""
  replicas: 2
  resources:
    requests: { cpu: 10m, memory: 64Mi }
    limits:   { cpu: 100m, memory: 128Mi }
