deployNodeAgent: true   # active Kopia (File System Backup)

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.0
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  existingSecret: velero-oci-credentials

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero-backups
      config:
        region: eu-frankfurt-1
        s3ForcePathStyle: "true"
        s3Url: https://frpwsda5ztd1.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
  # Pas de snapshot CSI disponible ici — volontairement vide
  volumeSnapshotLocation: []

schedules:
  daily:
    schedule: "0 3 * * *"
    template:
      ttl: "240h"               # rétention 10 jours
      includedNamespaces: ["*"]
      defaultVolumesToFsBackup: true   # force Kopia, pas de CSI
